import { NodeDef } from './types';

export const EXPR_NODE_DEFS: Record<string, NodeDef> = {
  compare: {
    category: 'compare',
    label: 'Compare',
    defaultOp: '==',
    ops: [
      { op: '==', label: '==' },
      { op: '!=', label: '!=' },
      { op: '>',  label: '>'  },
      { op: '<',  label: '<'  },
      { op: '>=', label: '>=' },
      { op: '<=', label: '<=' },
    ],
    inputs: [
      { name: 'A', label: 'A', type: 'any' },
      { name: 'B', label: 'B', type: 'any' },
    ],
    outputType: 'boolean',
    toCel: (op, inputs) => `(${inputs['A']} ${op} ${inputs['B']})`,
  },
  logic: {
    category: 'logic',
    label: 'Logic',
    defaultOp: '&&',
    ops: [
      { op: '&&', label: '&&' },
      { op: '||', label: '||' },
    ],
    inputs: [
      { name: 'A', label: 'A', type: 'boolean' },
      { name: 'B', label: 'B', type: 'boolean' },
    ],
    outputType: 'boolean',
    toCel: (op, inputs) => `(${inputs['A']} ${op} ${inputs['B']})`,
  },
  not: {
    category: 'not',
    label: 'Not',
    defaultOp: '!',
    ops: [{ op: '!', label: '!' }],
    inputs: [{ name: 'A', label: 'A', type: 'boolean' }],
    outputType: 'boolean',
    toCel: (_op, inputs) => `(!${inputs['A']})`,
  },
  conditional: {
    category: 'conditional',
    label: 'Conditional',
    defaultOp: '?:',
    ops: [{ op: '?:', label: '?:' }],
    inputs: [
      { name: 'condition', label: 'cond', type: 'boolean' },
      { name: 'then',      label: 'then', type: 'any'     },
      { name: 'else',      label: 'else', type: 'any'     },
    ],
    outputType: 'any',
    toCel: (_op, inputs) => `(${inputs['condition']} ? ${inputs['then']} : ${inputs['else']})`,
  },
  'optional-or-value': {
    category: 'optional-or-value',
    label: 'orValue',
    defaultOp: 'orValue',
    ops: [{ op: 'orValue', label: 'orValue' }],
    inputs: [
      { name: 'opt',     label: 'opt',     type: 'any' },
      { name: 'default', label: 'default', type: 'any' },
    ],
    outputType: 'any',
    toCel: (_op, inputs) => `${inputs['opt']}.orValue(${inputs['default']})`,
  },
  'string-replace': {
    category: 'string-replace',
    label: 'Replace',
    defaultOp: 'replace',
    ops: [{ op: 'replace', label: 'replace' }],
    inputs: [
      { name: 'str',  label: 'str',  type: 'string' },
      { name: 'from', label: 'from', type: 'string' },
      { name: 'to',   label: 'to',   type: 'string' },
    ],
    outputType: 'string',
    toCel: (_op, inputs) => `${inputs['str']}.replace(${inputs['from']}, ${inputs['to']})`,
  },
  'string-concat': {
    category: 'string-concat',
    label: 'Concat',
    defaultOp: '+',
    ops: [{ op: '+', label: '+' }],
    inputs: [
      { name: 'A', label: 'A', type: 'string' },
      { name: 'B', label: 'B', type: 'string' },
    ],
    outputType: 'string',
    variadic: true,
    toCel: (_op, inputs) => {
      const parts = Object.keys(inputs).sort().map(k => inputs[k]).filter(v => v !== '""');
      return `(${parts.join(' + ')})`;
    },
  },
  'has-value': {
    category: 'has-value',
    label: 'hasValue',
    defaultOp: 'hasValue',
    ops: [{ op: 'hasValue', label: 'hasValue' }],
    inputs: [
      { name: 'opt', label: 'opt', type: 'any' },
    ],
    outputType: 'boolean',
    toCel: (_op, inputs) => `${inputs['opt']}.hasValue()`,
  },
  exists: {
    category: 'exists',
    label: 'exists',
    defaultOp: 'exists',
    ops: [{ op: 'exists', label: 'exists' }],
    inputs: [
      { name: 'collection', label: 'list', type: 'array' },
      { name: 'var',        label: 'var',  type: 'any'   },
      { name: 'pred',       label: 'pred', type: 'any'   },
    ],
    outputType: 'boolean',
    hasPredicate: true,
    predicatePort: 'pred',
    toCel: (_op, inputs) => `${inputs['collection']}.exists(${inputs['var']}, ${inputs['pred']})`,
  },
  map: {
    category: 'map',
    label: 'map',
    defaultOp: 'map',
    ops: [{ op: 'map', label: 'map' }],
    inputs: [
      { name: 'collection', label: 'list', type: 'array' },
      { name: 'var',        label: 'var',  type: 'any'   },
      { name: 'expr',       label: 'expr', type: 'any'   },
    ],
    outputType: 'array',
    hasPredicate: true,
    predicatePort: 'expr',
    toCel: (_op, inputs) => `${inputs['collection']}.map(${inputs['var']}, ${inputs['expr']})`,
  },
  filter: {
    category: 'filter',
    label: 'filter',
    defaultOp: 'filter',
    ops: [{ op: 'filter', label: 'filter' }],
    inputs: [
      { name: 'collection', label: 'list', type: 'array'   },
      { name: 'var',        label: 'var',  type: 'any'     },
      { name: 'pred',       label: 'pred', type: 'boolean' },
    ],
    outputType: 'array',
    hasPredicate: true,
    predicatePort: 'pred',
    toCel: (_op, inputs) => `${inputs['collection']}.filter(${inputs['var']}, ${inputs['pred']})`,
  },
  all: {
    category: 'all',
    label: 'all',
    defaultOp: 'all',
    ops: [{ op: 'all', label: 'all' }],
    inputs: [
      { name: 'collection', label: 'list', type: 'array'   },
      { name: 'var',        label: 'var',  type: 'any'     },
      { name: 'pred',       label: 'pred', type: 'boolean' },
    ],
    outputType: 'boolean',
    hasPredicate: true,
    predicatePort: 'pred',
    toCel: (_op, inputs) => `${inputs['collection']}.all(${inputs['var']}, ${inputs['pred']})`,
  },
  sortBy: {
    category: 'sortBy',
    label: 'sortBy',
    defaultOp: 'sortBy',
    ops: [{ op: 'sortBy', label: 'sortBy' }],
    inputs: [
      { name: 'collection', label: 'list', type: 'array' },
      { name: 'var',        label: 'var',  type: 'any'   },
      { name: 'expr',       label: 'key',  type: 'any'   },
    ],
    outputType: 'array',
    hasPredicate: true,
    predicatePort: 'expr',
    toCel: (_op, inputs) => `${inputs['collection']}.sortBy(${inputs['var']}, ${inputs['expr']})`,
  },
  join: {
    category: 'join',
    label: 'join',
    defaultOp: 'join',
    ops: [{ op: 'join', label: 'join' }],
    inputs: [
      { name: 'list', label: 'list', type: 'array'  },
      { name: 'sep',  label: 'sep',  type: 'string' },
    ],
    outputType: 'string',
    toCel: (_op, inputs) => `${inputs['list']}.join(${inputs['sep']})`,
  },
  size: {
    category: 'size',
    label: 'size',
    defaultOp: 'size',
    ops: [{ op: 'size', label: 'size' }],
    inputs: [
      { name: 'val', label: 'val', type: 'any' },
    ],
    outputType: 'integer',
    toCel: (_op, inputs) => `size(${inputs['val']})`,
  },
  split: {
    category: 'split',
    label: 'split',
    defaultOp: 'split',
    ops: [{ op: 'split', label: 'split' }],
    inputs: [
      { name: 'str', label: 'str', type: 'string' },
      { name: 'sep', label: 'sep', type: 'string' },
    ],
    outputType: 'array',
    toCel: (_op, inputs) => `${inputs['str']}.split(${inputs['sep']})`,
  },
  'string-case': {
    category: 'string-case',
    label: 'Case',
    defaultOp: 'lowerAscii',
    ops: [
      { op: 'lowerAscii', label: 'lower' },
      { op: 'upperAscii', label: 'upper' },
      { op: 'trim',       label: 'trim'  },
      { op: 'reverse',    label: 'rev'   },
    ],
    inputs: [
      { name: 'str', label: 'str', type: 'string' },
    ],
    outputType: 'string',
    toCel: (op, inputs) => `${inputs['str']}.${op}()`,
  },
  'string-pred': {
    category: 'string-pred',
    label: 'StrTest',
    defaultOp: 'contains',
    ops: [
      { op: 'contains',   label: 'contains' },
      { op: 'startsWith', label: 'starts'   },
      { op: 'endsWith',   label: 'ends'     },
      { op: 'matches',    label: 'matches'  },
      { op: 'find',       label: 'find'     },
    ],
    inputs: [
      { name: 'str',     label: 'str',  type: 'string' },
      { name: 'pattern', label: 'pat',  type: 'string' },
    ],
    outputType: 'any',
    toCel: (op, inputs) => `${inputs['str']}.${op}(${inputs['pattern']})`,
  },
  substring: {
    category: 'substring',
    label: 'substr',
    defaultOp: 'substring',
    ops: [{ op: 'substring', label: 'substr' }],
    inputs: [
      { name: 'str',   label: 'str',   type: 'string'  },
      { name: 'start', label: 'start', type: 'integer' },
      { name: 'end',   label: 'end',   type: 'integer' },
    ],
    outputType: 'string',
    toCel: (_op, inputs) => `${inputs['str']}.substring(${inputs['start']}, ${inputs['end']})`,
  },
  'type-convert': {
    category: 'type-convert',
    label: 'Convert',
    defaultOp: 'string',
    ops: [
      { op: 'string', label: 'str'  },
      { op: 'int',    label: 'int'  },
      { op: 'bool',   label: 'bool' },
    ],
    inputs: [
      { name: 'val', label: 'val', type: 'any' },
    ],
    outputType: 'any',
    toCel: (op, inputs) => `${op}(${inputs['val']})`,
  },
  math: {
    category: 'math',
    label: 'Math',
    defaultOp: '*',
    ops: [
      { op: '*', label: '×' },
      { op: '/', label: '÷' },
      { op: '%', label: '%' },
    ],
    inputs: [
      { name: 'A', label: 'A', type: 'number' },
      { name: 'B', label: 'B', type: 'number' },
    ],
    outputType: 'number',
    toCel: (op, inputs) => `(${inputs['A']} ${op} ${inputs['B']})`,
  },
  'list-unary': {
    category: 'list-unary',
    label: 'List',
    defaultOp: 'sort',
    ops: [
      { op: 'sort',     label: 'sort'  },
      { op: 'flatten',  label: 'flat'  },
      { op: 'distinct', label: 'uniq'  },
      { op: 'reverse',  label: 'rev'   },
    ],
    inputs: [
      { name: 'list', label: 'list', type: 'array' },
    ],
    outputType: 'array',
    toCel: (op, inputs) => `${inputs['list']}.${op}()`,
  },
  'list-aggregate': {
    category: 'list-aggregate',
    label: 'Agg',
    defaultOp: 'sum',
    ops: [
      { op: 'sum', label: 'sum' },
      { op: 'min', label: 'min' },
      { op: 'max', label: 'max' },
    ],
    inputs: [
      { name: 'list', label: 'list', type: 'array' },
    ],
    outputType: 'any',
    toCel: (op, inputs) => `${inputs['list']}.${op}()`,
  },
  merge: {
    category: 'merge',
    label: 'merge',
    defaultOp: 'merge',
    ops: [{ op: 'merge', label: 'merge' }],
    inputs: [
      { name: 'base',     label: 'base', type: 'object' },
      { name: 'override', label: 'over', type: 'object' },
    ],
    outputType: 'object',
    toCel: (_op, inputs) => `${inputs['base']}.merge(${inputs['override']})`,
  },
  'json-marshal': {
    category: 'json-marshal',
    label: 'json.marshal',
    defaultOp: 'marshal',
    ops: [{ op: 'marshal', label: 'marshal' }],
    inputs: [
      { name: 'val', label: 'val', type: 'any' },
    ],
    outputType: 'string',
    toCel: (_op, inputs) => `json.marshal(${inputs['val']})`,
  },
  'json-unmarshal': {
    category: 'json-unmarshal',
    label: 'json.unmarshal',
    defaultOp: 'unmarshal',
    ops: [{ op: 'unmarshal', label: 'unmarshal' }],
    inputs: [
      { name: 'str', label: 'str', type: 'string' },
    ],
    outputType: 'any',
    toCel: (_op, inputs) => `json.unmarshal(${inputs['str']})`,
  },
  'lists-range': {
    category: 'lists-range',
    label: 'lists.range',
    defaultOp: 'range',
    ops: [{ op: 'range', label: 'range' }],
    inputs: [
      { name: 'n', label: 'n', type: 'integer' },
    ],
    outputType: 'array',
    toCel: (_op, inputs) => `lists.range(${inputs['n']})`,
  },
  'raw-template': {
    category: 'raw-template',
    label: 'Template',
    defaultOp: 'template',
    ops: [{ op: 'template', label: 'T' }],
    inputs: [],
    outputType: 'string',
    toCel: (_op, inputs) => inputs['value'] ?? '',
  },
};
